### ISSUE TITLE
bsseq.check

### ISSUE THREAD

**Issue by Yikun** [Yikun/BBS#37]
https://yikun.github.io/bioconductor-0301/report/bsseq/kunpeng1-checksrc.html

**Comment by martin-g** [comment]
Fails the same on:
* Mac ARM64 - https://bioconductor.org/checkResults/3.17/bioc-LATEST/bsseq/merida1-checksrc.html
* Windows - https://bioconductor.org/checkResults/3.17/bioc-LATEST/bsseq/palomino3-checksrc.html

On Linux x86_64 it fails with at BUILD time with unrelated error - https://bioconductor.org/checkResults/3.17/bioc-LATEST/bsseq/nebbiolo1-buildsrc.html
Maybe it will fail the same on the next report run for Linux ARM64 ?!

**Comment by martin-g** [comment]
https://bioconductor.org/checkResults/3.18/bioc-LATEST/bsseq/kunpeng2-checksrc.html is fully green!
